### ISSUE TITLE
Erroneous example for `getEventsObservableFromJournal` in README.md

### ISSUE THREAD

**Issue by actinium15** [adobe/aio-lib-events#6]
[README](https://github.com/adobe/aio-lib-events#usage) of the project includes an example for "Using the poller for journalling", which suggests invocation of `.unsubscribe` on object returned by RxJS' `Observable.subscribe`'s returned by `EventsCoreAPI.getEventsObservableFromJournal`.

### Expected Behaviour
`journalling.unsubscribe` should stop the stream of events being emitted after the timeout expires.

### Actual Behaviour
```
  setTimeout(() => this.subscription.unsubscribe(), 1000)
                                     ^

TypeError: Cannot read property 'unsubscribe' of undefined
    at Timeout._onTimeout (/Users/ashishc/repo/aio-journal-consumer/journalConsumer.js:20:38)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

### Reproduce Scenario (including but not limited to)
Execution of the sample-code for project README is sufficient to demonstrate the issue.

#### Steps to Reproduce
"Using the poller for journalling" sample-code from [README](https://github.com/adobe/aio-lib-events#usage), set a valid timeout and wait for that duration to pass after invocation of the code.

#### Platform and Version
macOS 10.15.4
node v13.13.0
npm v6.16.4

#### Sample Code that illustrates the problem
"Using the poller for journalling" sample-code from [README](https://github.com/adobe/aio-lib-events#usage)

#### Logs taken while reproducing problem
N/A

**Comment by sangeetha5491** [comment]
Thanks for reporting this issue. I will take a look at it.

**Comment by sangeetha5491** [comment]
This issue has been fixed. Please try it out.
